name: ci

on:
  push:
    branches:
      - "*"
    branches_ignore:
      - refs/tags/*

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Make repo name
        run: echo "REPO_NAME=$(echo ${{ github.repository }})" >> $GITHUB_ENV
      - name: Login to Docker registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PWD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${{ env.REPO_NAME }}:${{ github.sha }}
            ${{ env.REPO_NAME }}:latest
